-- auto-generated definition
CREATE TABLE IF NOT EXISTS client
(
    doc_number       integer      not null
        unique,
    id               bigint generated by default as identity
        primary key,
    address          varchar(255) not null,
    city             varchar(255) not null,
    doc_type         varchar(255) not null,
    first_name       varchar(255) not null,
    last_name        varchar(255) not null,
    phone            varchar(255) not null,
    second_last_name varchar(255) not null,
    second_name      varchar(255) not null
);

alter table client
    owner to postgres;

