version: "3.8"

services:
  client_app:
    container_name: client_app
    image: client-java-app:1.0.0
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://clients_db:5432/clients_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Admin123
    depends_on:
      - clients_db
  clients_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "clients_db"
      POSTGRES_PASSWORD: "Admin123"
    volumes:
      - postgresql_db:/var/lib/pgsql/data

volumes:
  postgresql_db: